home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('email/<int:email_id>/', views.EmailDetailView.as_view(), name='email_detail'),
    path('send_email/', views.SendEmailView.as_view(), name='send_email'),
    path('send_email/<str:receiver_email>/', views.SendEmailView.as_view(), name='send_email_to'),
    path('delete_email/<int:email_id>/', views.DeleteEmailView.as_view(), name='delete_email'),
    path('set_unread/<int:email_id>/', views.SetUnreadView.as_view(), name='set_unread'),
    path('set_phishing/<int:email_id>/', views.SetPhishingView.as_view(), name='set_phishing'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('visualizeTree/', include('visualizeTree.urls')),
    path('', include('home.urls')),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Email(models.Model):
    id = models.AutoField(primary_key=True)
    sender_email = models.EmailField(max_length=254)
    receiver_email = models.EmailField(max_length=254)
    subject = models.CharField(max_length=255)
    body = models.TextField()
    send_date = models.DateTimeField(auto_now_add=True)
    is_phishing = models.BooleanField(default=False)
    is_read = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)

class UserEmail(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.ForeignKey(Email, on_delete=models.CASCADE)
    is_read = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)

    class Meta:
        unique_together = ('user', 'email')  # Ensure one entry per user-email pair

home/forms.py
from django import forms
from .models import Email

class EmailForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = ['sender_email', 'receiver_email', 'subject', 'body', 'is_phishing']

home/views.py
from django.shortcuts import redirect, render
from home.forms import EmailForm
from .models import Email, UserEmail
from django.contrib.auth.models import User
from django.views import View
from visualizeTree.LearningDecisionTree import load_tree, predict, analyze_mail

tree = load_tree()

# Create your views here.

class IndexView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('login')
        
        title = 'Inbox'
        label = request.GET.get('label')
        user_emails = UserEmail.objects.filter(user=request.user, 
                                               is_deleted=False, 
                                               email__receiver_email=request.user.email
                                               ).select_related('email').order_by('-email__send_date')
        match label:
            case None:
                title = 'Inbox'
                user_emails = user_emails.filter(email__is_phishing=False)
            case 'phishing':
                title = 'Phishing'
                user_emails = user_emails.filter(email__is_phishing=True)
            case 'sent':
                title = 'Sent'
                user_emails = UserEmail.objects.filter(user=request.user, 
                                                       is_deleted=False, 
                                                       email__sender_email=request.user.email
                                                       ).select_related('email').order_by('-email__send_date')
        
        unread_count = UserEmail.objects.filter(user=request.user, is_read=False, is_deleted=False, email__is_phishing=False).count()
        phishing_unread_count = UserEmail.objects.filter(user=request.user, is_read=False, is_deleted=False, email__is_phishing=True).count()
        context = {
                    'user_emails': user_emails,
                    'title': title,
                    'unread_count': unread_count,
                    'phishing_unread_count': phishing_unread_count,
                }

        return render(request, 'home/index.html', context)
    
class EmailDetailView(View):
    def get(self, request, email_id):
        if not request.user.is_authenticated:
            return redirect('login')
        email = Email.objects.get(id=email_id)
        UserEmail.objects.filter(user=request.user, email=email).update(is_read=True)
        return render(request, 'home/email_details.html', {'email': email})
    
class SendEmailView(View):
    def post(self, request):
        if not request.user.is_authenticated:
            return redirect('login')
        
        form = EmailForm(request.POST)

        if form.is_valid():
            email = form.save(commit=False)
            predicted_label = predict(analyze_mail(form.cleaned_data['body']), tree)[0]
            print(f"Predicted label: {predicted_label}")
            email.is_phishing = predicted_label == '1'
            email.save()

            # Link email to sender and receiver
            UserEmail.objects.create(
                user=request.user,
                email=email,
                is_read=True
            )
            # MultipleObjectsReturned at /send_email/ get() returned more than one UserEmail -- it returned 8!

            UserEmail.objects.create(
                user=User.objects.get(email=form.cleaned_data['receiver_email']),
                email=email
            )
            
            return redirect('home:index')
        return redirect('home:send_email')
    
    def get(self, request, receiver_email=""):
        if not request.user.is_authenticated:
            return redirect('login')
        form = EmailForm()
        return render(request, 'home/send_email.html', {'form': form, 'receiver_email': receiver_email})

class DeleteEmailView(View):
    def post(self, request, email_id):
        if not request.user.is_authenticated:
            return redirect('login')
        
        user_email = UserEmail.objects.get(user=request.user, email__id=email_id)
        user_email.is_deleted = True
        user_email.save()
        return redirect('home:index')
    
class SetUnreadView(View):
    def post(self, request, email_id):
        if not request.user.is_authenticated:
            return redirect('login')
        
        user_email = UserEmail.objects.get(user=request.user, email__id=email_id)
        user_email.is_read = False
        user_email.save()
        return redirect('home:index')
    
class SetPhishingView(View):
    def post(self, request, email_id):
        if not request.user.is_authenticated:
            return redirect('login')
        
        email = Email.objects.get(id=email_id)
        email.is_phishing = True
        email.save()
        return redirect('home:index')

home/templates/home/email_details.html
{% extends 'base/base.html' %}

{% block title %}Email Details{% endblock %}

{% load static %}

{% block main_content %}

<!-- Email details -->
<div class="email-view">
    <div class="email-header">
        <h2>{{ email.subject }}</h2>
        <p><strong>From:</strong> {{ email.sender_email }}</p>
        <p><strong>To:</strong> {{ email.receiver_email }}</p>
        <p><strong>Date:</strong> {{ email.send_date }}</p>
    </div>
    <div class="email-body">
        <p>{{ email.body }}</p>
    </div>
    <div class="email-actions">
        <form action="{% url 'home:send_email_to' email.sender_email %}" method="get" style="display:inline;">
            <button type="submit">Reply</button>
        </form>
        
        <form action="{% url 'home:set_unread' email.id %}" method="post" style="display:inline;">
            {% csrf_token %}
            <button type="submit">Mark as Unread</button>
        </form>

        <form action="{% url 'home:set_phishing' email.id %}" method="post" style="display:inline;">
            {% csrf_token %}
            <button type="submit">Mark as Phishing</button>
        </form>
        <form action="{% url 'home:delete_email' email.id %}"
                onsubmit="return confirm('Delete this email?')" 
                method="post" 
                style="display:inline; margin-left: auto;">
            {% csrf_token %}
            <button type="submit" style="background-color: red; color: white;">Delete</button>
        </form>
    </div>
</div>

{% endblock %}

home/templates/home/index.html
{% extends 'base/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% load static %}

{% block main_content %}
<div class="email-list">
    <h2>{{ title }}</h2>
    <ul>
        {% for user_email in user_emails %}
        <li class="{% if not user_email.is_read %}unread{% endif %}">
            <a href="{% url 'home:email_detail' user_email.email.id %}" class="email-item-link">
                <div class="email-sender">{{ user_email.email.sender_email }}</div>
                <div class="email-subject">{{ user_email.email.subject }}</div>
                <div class="email-date">{{ user_email.email.send_date}}</div>
            </a>
        </li>
        {% empty %}
        <li>No emails available.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

home/templates/home/send_email.html
{% extends 'base/base.html' %}

{% block title %}Send Email{% endblock %}

{% load static %}

{% block main_content %}
<div class="compose">
    <h2>New Message</h2>
    <form action="{% url 'home:send_email' %}" method="post">
        {% csrf_token %}
        <div>From:</div>
        <input type="email" name="sender_email" value="{{ request.user.email }}" required readonly>
        <div>To:</div>
        <input type="email" name="receiver_email" placeholder="To" value="{{ receiver_email }}" required>
        <div>Subject:</div>
        <input type="text" name="subject" placeholder="Subject" required>
        <div>Message:</div>
        <textarea name="body" placeholder="Message" rows="10" required></textarea>
        <div class="form-actions">
            <button type="submit">Send</button>
        </div>
    </form>
</div>
{% endblock %}